"""Add field status in call_records

Revision ID: bcac2f94311d
Revises: 1d106380f117
Create Date: 2024-11-17 17:14:02.058547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcac2f94311d'
down_revision: Union[str, None] = '1d106380f117'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_records', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('call_records', 'status')
    # ### end Alembic commands ###
