"""Remove field total_amount

Revision ID: c8c2528e60d6
Revises: bcac2f94311d
Create Date: 2024-11-18 11:30:05.853284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8c2528e60d6'
down_revision: Union[str, None] = 'bcac2f94311d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phone_bills', 'total_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone_bills', sa.Column('total_amount', sa.FLOAT(), nullable=False))
    # ### end Alembic commands ###
